### ISSUE TITLE
Retrieving the venues that were previously added on the Navigine portal

### ISSUE THREAD

**Issue by judykhairalla** [Navigine/Indoor-Navigation-Flutter-SDK#2]
### Expected behavior
Loading venues that were previously added on the Navigine portal via the `onLoactionLoaded` method as follows:

**In example/lib/main.dart**
```
var locationManager = LocationManager.init();
locationManager.setListener(LocationListener(
  onLocationLoaded: (location) {
    print(location);
    venues = location.sublocations.first.venues;
  },
));
```
### Current behavior
The example source code's `onLocationLoaded` function only gets called when the chosen sublocation doesn't have predefined venues from the portal.

### Debugging results
The SDK's `onLoactionLoaded`  method internally receives a JSON response with the location and sublocations; however, the venues are returned under the label "eddystones". In addition, the venues are returned without IDs. Consequently, the workaround I am currently using is reading the eddystones as venues as follows:
**In lib/src/types/sublocation.dart**
`venues: json['eddystones'].map<Venue>((el) => Venue._fromJson(el)).toList()`
and generating venue IDs in the SDK instead of reading them from the JSON response.
Is there another way to fix this issue?

**Comment by PavelTychinin** [comment]
done. Check new version of SDK
