### ISSUE TITLE
Navigine Indoor Navigation Flutter SDK, W/FinalizerDaemon(12602): type=1400 audit(0.0:277645): avc: denied { getopt } for path="/dev/socket/usap_pool_primary"

### ISSUE THREAD

**Issue by cmtan-2000** [Navigine/Indoor-Navigation-Flutter-SDK#4]
Hi, I am integrating Navigine Flutter SDK with my Flutter project to develop an indoor navigation system. I followed the guide from the Navigine website on how to start the navigation. I created and sketched the floor plan using the tools provided by the Navigine, and I want to load the map on my Flutter project. I had added my user hash to the project, and when I ran the Navigine Flutter SDK, the map was not shown in the apps, as shown below. 

![86362e08-6438-4bcc-a768-4717a442f0fb](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/d7cb1d2a-115f-41ea-a94d-afd505f4e138)

This is the information shown in the terminal, and I realize there is something that got denied. It may cause the map not to load to my app. Can anyone help me? 

![bug-01](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/8a0fc457-8980-4fda-aff4-e5f22e74faba)
![bug-02](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/9322c59f-b4f9-4965-8708-c885018229a2)

**Comment by cmtan-2000** [comment]
Hi, can anyone help me to resolve this matter?

**Comment by PavelTychinin** [comment]
Hi, have you called setLocationId and setSublocationId with corresponding ids?

As far as I see - there are no errors coming from NavigineSDK side

**Comment by cmtan-2000** [comment]
Hi, PavelTychinin, thanks for the response, I realized that I missed setting the locationId and sublocationId in the application.
