### ISSUE TITLE
Navigine::network::http::RequestHandler::RequestHandler: Request: id=4 uri=https://ips.navigine.com/mobile/v0/devices/upload

### ISSUE THREAD

**Issue by cmtan-2000** [Navigine/Indoor-Navigation-Flutter-SDK#5]
Hi, may I ask why this error is always prompted in the debug consoles? Is there any solution to solve this?
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/a1cb454e-23d6-4f86-ae9a-1a9edf341a55)

After that, when I tap the mapObject in my application, why it does not trigger the function onMapFeaturePick
![WhatsApp Image 2024-04-01 at 01 10 27_13f4914e](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/8d4203a8-9213-4914-9d4e-b34a3ec07567)

Other than this, when I tapping the map, the debug console prompts these, "navigine::view::MarkerManager::buildMesh: Invalid style:"
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/48f39008-1c3f-4481-8172-56903fc34d26)
Is there any solution to solve it?

**Comment by cmtan-2000** [comment]
hi PavelTyhcinin, when i tapping on the object, it does not call the pickMapFeatureAt
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/5474bf19-bb6f-4df1-a3da-4a8122030c84)


When I tapped the object, it does not trigger the call pickMapFeatureAt as the picture shown below.
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/1cd13cf7-8adf-4b49-b43c-ff3a20a50cd6)

Can help me figure out why it does not working?

**Comment by PavelTychinin** [comment]
can you put here full log from startup ?

**Comment by cmtan-2000** [comment]
I am sorry that I used the improper ways to show the full log of application startup, but here is the full 
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/0b527fb6-c6da-411e-a24f-6f1024a53e23)
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/cad5d17f-3c2b-478f-9b0b-58418f1aeea1)
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/9d5e6f2c-f826-4429-bdec-5bdd3e1972c8)
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/a780fee9-ac44-49c4-ac20-ef2c02d78793)
![image](https://github.com/Navigine/Indoor-Navigation-Flutter-SDK/assets/68101246/e9dd4c46-a44e-48b7-8841-d170d87ec0d9)

**Comment by cmtan-2000** [comment]
Hi, is there any update here?

**Comment by PavelTychinin** [comment]
Hi, yes. Check latest update. Should work now

**Comment by cmtan-2000** [comment]
Thanks, now its working
